openapi: "3.0.2"
info:
  title: ISG Guard Restful API
  version: "1.0"
servers:
  - url: http://localhost:8001/api/v1
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
